### ISSUE TITLE
Add quick action `/milestone`

### ISSUE THREAD

**Issue by xunleii** [xunleii/github-quick-actions#63]
### Quick Action command

`/milestone %milestone`

### On events

- [X] Issue description (issue)
- [X] Issue comment (issue_comment)
- [X] Pull request description (pull_request)
- [X] Pull request comment (issue_comment)
- [ ] Pull request review comment (pull_request_review_comment)

### Description

Set milestone.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
